version: '3.8'

services:
  deepagents-printshop:
    build: .
    container_name: deepagents-printshop
    volumes:
      - .:/app
      - deepagents-data:/app/.deepagents
    env_file:
      - .env
    stdin_open: true
    tty: true
    working_dir: /app

volumes:
  deepagents-data:
